### PR TITLE
Updates project reflecting the latest changes

### PR DESCRIPTION
**Pull request by vecerek**
New process of downloading a course:
- open video page of the course
- read videos' links into an array
- simulate a click on each of the videos
- read the video's url
- close the video player
- download and repeat for the whole course

Also added some puts, so the user knows what is currently going on.

### CODE REVIEW

**Comment by will-clarke** [comment]
Awesome! This works really well. Thanks for contributing :smiley: :+1:

**Comment by vecerek** [comment]
You're welcome :) The screencast downloading still doesn't work . I thought of complete refactoring. Turning the code much more into OO by creating some additional classes:
- Course
- Video
  - Lesson < Video
  - Screencast < Video

I think, it would raise the quality of the implementation. Do you agree?

**Comment by will-clarke** [comment]
Yes! I completely agree.. I was just looking over this code and thought that it needed a major overhaul. It's really imperative at the moment. I think this is the way to go! :smiley:

**Comment by vecerek** [comment]
Alright, I will create a new branch and code the skeleton as soon as I have some free time. Maybe later today.

**Pull request merged**
